# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-01-10 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncorrectClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MLCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_model_json', models.TextField(blank=True)),
                ('topic_model_cyberbullying_json', models.TextField(blank=True)),
                ('affective_counts_json', models.TextField(blank=True)),
                ('affective_counts_cyberbullying_json', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedSocialMediaMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('username', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('has_bullying', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Viewer', 'Viewer'), ('Moderatior', 'Moderatior')], default='Viewer', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='incorrectclassification',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cbd.ProcessedSocialMediaMessage'),
        ),
        migrations.AddField(
            model_name='incorrectclassification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
